---
  - name: Install Apache and Upload my WebPage
    hosts: all
    become: yes

    vars:
       source_file: ./MyWebSite/index.html
       destin_file: /var/www/html/

    tasks:

      - name: Show LINUX Version
        debug: var=ansible_os_family

      - block: #=====BLOCK FOR REDHAT=====

          - name: Install Apache WebServer for Redhat
            yum: name=httpd state=latest
           
          - name: Copy MyHomePage to Servers
            copy: src={{ source_file }} dest={{ destin_file }} mode=0555
            notify: Restart Apache RedHat

          - name: Start Apache and Enable it for RedHat
            service: name=httpd state=started enabled=yes
        when: ansible_os_family == "Redhat"
        
      - block: #=====BLOCK FOR DEBIAN=====

           - name: Install Apache WebServer for Debian
             apt: name=apache2 state=latest
             
           - name: Copy MyHomePage to Servers
             copy: src={{ source_file }} dest={{ destin_file }} mode=0555
             notify: Restart Apache Debian

           - name: Start Apache and Enable it for Debian
             service: name=apache2 state=started enabled=yes
        when: ansible_os_family == "Debian"


    handlers:
      - name: Restart Apache RedHat
        service: name=httpd state=restarted
        
      - name: Restart Apache Debian        
        service: name=apache2 state=restarted
        


