---
  - name: Install Apache and Upload my WebPage
    hosts: all
    become: yes

    vars:
       source_file: ./MyWebSite/index.html
       destin_file: /var/www/html/

    tasks:
      - name: Install Apache WebServer
        yum: name=apache2 state=latest

      - name: Copy MyHomePage to Servers
        copy: src={{ source_file }} dest={{ destin_file }} mode=0555
        notify: Restart Apache

      - name: Start Apache and Enable it on the every boot
        service: name=apache2 state=started enabled=yes

    handlers:
      - name: Restart Apache
        service: name=apache2 state=restarted
